#population old
# add population statistics for rate per 100,000 calculations
df <- df |> 
  mutate(population = case_when( # using 2021 population estimates for Canadians age 12-17 and 18+ from https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1710000501
    region == "Newfoundland and Labrador" & youth_adult == "Youth" ~ 31422,
    region == "Newfoundland and Labrador" & youth_adult == "Adult" ~ 436162,
    region == "Prince Edward Island" & youth_adult == "Youth" ~ 10973,
    region == "Prince Edward Island" & youth_adult == "Adult" ~ 134763,
    region == "Nova Scotia" & youth_adult == "Youth" ~ 57999,
    region == "Nova Scotia" & youth_adult == "Adult" ~ 825690,
    region == "New Brunswick" & youth_adult == "Youth" ~ 48486,
    region == "New Brunswick" & youth_adult == "Adult" ~ 654634,
    region == "Quebec" & youth_adult == "Youth" ~ 530147,
    region == "Quebec" & youth_adult == "Adult" ~ 6998140,
    region == "Ontario" & youth_adult == "Youth" ~ 961924,
    region == "Ontario" & youth_adult == "Adult" ~ 12059243,
    region == "Manitoba" & youth_adult == "Youth" ~ 101605,
    region == "Manitoba" & youth_adult == "Adult" ~ 1081274,
    region == "Saskatchewan" & youth_adult == "Youth" ~ 89410,
    region == "Saskatchewan" & youth_adult == "Adult" ~ 908718,
    region == "Alberta" & youth_adult == "Youth" ~ 322691,
    region == "Alberta" & youth_adult == "Adult" ~ 3470048,
    region == "British Columbia" & youth_adult == "Youth" ~ 303652,
    region == "British Columbia" & youth_adult == "Adult" ~ 4329311,
    region == "Yukon" & youth_adult == "Youth" ~ 2621,
    region == "Yukon" & youth_adult == "Adult" ~ 34823,
    region == "Northwest Territories" & youth_adult == "Youth" ~ 3519,
    region == "Northwest Territories" & youth_adult == "Adult" ~ 34904,
    region == "Nunavut" & youth_adult == "Youth" ~ 4444,
    region == "Nunavut" & youth_adult == "Adult" ~ 25141,
    region == "Canada" & youth_adult == "Youth" ~ 2468893,
    region == "Canada" & youth_adult == "Adult" ~ 30992851,
  ))